export const UNIVERSITIES = [
  "Bakı Dövlət Universiteti (BDU)",
  "Azərbaycan Dövlət İqtisad Universiteti (UNEC)",
  "Azərbaycan Dövlət Neft və Sənaye Universiteti (ADNSU)",
  "ADA Universiteti",
  "Azərbaycan Tibb Universiteti (ATU)",
  "Azərbaycan Texniki Universiteti (AzTU)",
  "Azərbaycan Dillər Universiteti (ADU)",
  "Bakı Mühəndislik Universiteti (BMU)",
  "Xəzər Universiteti",
  "Qərbi Kaspi Universiteti",
  "Bakı Slavyan Universiteti (BSU)",
  "Azərbaycan Dövlət Pedaqoji Universiteti (ADPU)",
  "Azərbaycan Memarlıq və İnşaat Universiteti (AzMİU)",
  "Bakı Ali Neft Məktəbi (BANM)",
  "Milli Aviasiya Akademiyası (MAA)",
  "Azərbaycan Turizm və Menecment Universiteti (ATMU)",
  "Naxçıvan Dövlət Universiteti (NDU)",
  "Gəncə Dövlət Universiteti (GDU)",
  "Sumqayıt Dövlət Universiteti (SDU)",
  "Lənkəran Dövlət Universiteti (LDU)",
  "Mingəçevir Dövlət Universiteti",
  "Azərbaycan Dövlət Mədəniyyət və İncəsənət Universiteti (ADMİU)",
  "Azərbaycan Dövlət Bədən Tərbiyəsi və İdman Akademiyası (ADBTİA)",
  "Dövlət Gömrük Komitəsinin Akademiyası",
  "Azərbaycan İlahiyyat İnstitutu",
  "Digər",
];

export const HOBBY_SUGGESTIONS = [
  "İdman",
  "Musiqi",
  "Kitab",
  "Səyahət",
  "Fotoqrafiya",
  "Rəsm",
  "Kinoteatr",
  "Startap",
  "Dil öyrənmə",
  "Oyun",
  "Volonteerlik",
];
